version: "3.8"

services:
  expense_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    image: expense_app
    container_name: expense_app_container
    command: python manage.py runserver 0.0.0.0:8000
